server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Si le fichier demandé n'existe pas, renvoie index.html (pour React/Vue/Angular)
        try_files $uri $uri/ /index.html;
    }

    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
        # Gestion des erreurs 404 (le router SPA prendra le relais)
    error_page 404 /index.html;
}
