# Image PHP 8.2
FROM php:8.2-cli

# Installer les extensions nécessaires
RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev libpng-dev libonig-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip

# Installer l'extension MongoDB pour PHP
RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Installer la CLI Symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

# Définir le dossier de travail
WORKDIR /var/www/html

# Copier le code du back
COPY ./backend /var/www/html

# Installer les dépendances Symfony
RUN composer install --no-interaction --optimize-autoloader

# Exposer le port 8000 (Symfony serve)
EXPOSE 8000

# Démarrer le serveur Symfony
CMD ["symfony", "serve", "--no-interaction", "--port=8000"]
