services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: oseznoel-front
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: oseznoel-back
    ports:
      - "${BACK_PORT}:8000"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MONGODB_URL: mongodb://mongo:27017
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
      - mongo
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    container_name: oseznoel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DATA_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: oseznoel-phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MY_ADMIN_PORT}:80"

  mongo:
    image: mongo:6.0
    container_name: oseznoel-mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: oseznoel-mongo-express
    restart: always
    ports:
      - "${MONGODB_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_SERVER}

volumes:
  db_data:
  mongo_data:
